# Generated by Django 4.1.7 on 2023-03-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='show_contact',
            field=models.BooleanField(default=True),
        ),
    ]
